[2024-11-27T12:28:28.321-0500] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-11-27T12:28:28.327-0500] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sensor_dag.wait_current_dag scheduled__2024-11-27T17:25:00+00:00 [queued]>
[2024-11-27T12:28:28.331-0500] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sensor_dag.wait_current_dag scheduled__2024-11-27T17:25:00+00:00 [queued]>
[2024-11-27T12:28:28.331-0500] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2024-11-27T12:28:28.344-0500] {taskinstance.py:2889} INFO - Executing <Task(ExternalTaskSensor): wait_current_dag> on 2024-11-27 17:25:00+00:00
[2024-11-27T12:28:28.351-0500] {logging_mixin.py:190} WARNING - /home/vanaprastha/anaconda3/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=33718) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-11-27T12:28:28.352-0500] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'sensor_dag', 'wait_current_dag', 'scheduled__2024-11-27T17:25:00+00:00', '--job-id', '72', '--raw', '--subdir', 'DAGS_FOLDER/PART 3/Sensor/sensor_dag.py', '--cfg-path', '/tmp/tmpnn0zvg4y']
[2024-11-27T12:28:28.352-0500] {standard_task_runner.py:72} INFO - Started process 33725 to run task
[2024-11-27T12:28:28.352-0500] {standard_task_runner.py:105} INFO - Job 72: Subtask wait_current_dag
[2024-11-27T12:28:28.376-0500] {task_command.py:467} INFO - Running <TaskInstance: sensor_dag.wait_current_dag scheduled__2024-11-27T17:25:00+00:00 [running]> on host VanaPrastha
[2024-11-27T12:28:28.424-0500] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='sensor_dag' AIRFLOW_CTX_TASK_ID='wait_current_dag' AIRFLOW_CTX_EXECUTION_DATE='2024-11-27T17:25:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-11-27T17:25:00+00:00'
[2024-11-27T12:28:28.425-0500] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-11-27T12:28:28.425-0500] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-11-27T12:28:28.425-0500] {logging_mixin.py:190} INFO - Current task name:wait_current_dag state:running start_date:2024-11-27 17:28:28.328284+00:00
[2024-11-27T12:28:28.425-0500] {logging_mixin.py:190} INFO - Dag name:sensor_dag and current dag run status:running
[2024-11-27T12:28:28.425-0500] {taskinstance.py:731} INFO - ::endgroup::
[2024-11-27T12:28:28.425-0500] {baseoperator.py:416} WARNING - ExternalTaskSensor.execute cannot be called outside TaskInstance!
[2024-11-27T12:28:28.425-0500] {external_task.py:258} INFO - Poking for tasks ['end_task'] in dag sensor_sleep on 2024-11-27T17:25:00+00:00 ... 
[2024-11-27T12:28:28.426-0500] {logging_mixin.py:190} WARNING - /home/vanaprastha/anaconda3/lib/python3.12/site-packages/airflow/utils/session.py:97 DeprecationWarning: This method is deprecated and will be removed in future.
[2024-11-27T12:28:33.429-0500] {external_task.py:258} INFO - Poking for tasks ['end_task'] in dag sensor_sleep on 2024-11-27T17:25:00+00:00 ... 
[2024-11-27T12:28:38.434-0500] {external_task.py:258} INFO - Poking for tasks ['end_task'] in dag sensor_sleep on 2024-11-27T17:25:00+00:00 ... 
[2024-11-27T12:28:43.440-0500] {external_task.py:258} INFO - Poking for tasks ['end_task'] in dag sensor_sleep on 2024-11-27T17:25:00+00:00 ... 
[2024-11-27T12:28:48.445-0500] {external_task.py:258} INFO - Poking for tasks ['end_task'] in dag sensor_sleep on 2024-11-27T17:25:00+00:00 ... 
[2024-11-27T12:28:53.451-0500] {external_task.py:258} INFO - Poking for tasks ['end_task'] in dag sensor_sleep on 2024-11-27T17:25:00+00:00 ... 
[2024-11-27T12:28:58.454-0500] {external_task.py:258} INFO - Poking for tasks ['end_task'] in dag sensor_sleep on 2024-11-27T17:25:00+00:00 ... 
[2024-11-27T12:29:00.021-0500] {local_task_job_runner.py:245} INFO - ::endgroup::
[2024-11-27T12:29:00.029-0500] {process_utils.py:132} INFO - Sending 15 to group 33725. PIDs of all processes in the group: [33725]
[2024-11-27T12:29:00.029-0500] {process_utils.py:87} INFO - Sending the signal 15 to group 33725
[2024-11-27T12:29:00.029-0500] {taskinstance.py:3093} ERROR - Received SIGTERM. Terminating subprocesses.
[2024-11-27T12:29:00.035-0500] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/vanaprastha/anaconda3/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vanaprastha/anaconda3/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vanaprastha/anaconda3/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vanaprastha/anaconda3/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vanaprastha/anaconda3/lib/python3.12/site-packages/airflow/sensors/external_task.py", line 348, in execute
    super().execute(context)
  File "/home/vanaprastha/anaconda3/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vanaprastha/anaconda3/lib/python3.12/site-packages/airflow/sensors/base.py", line 334, in execute
    time.sleep(self._get_next_poke_interval(started_at, run_duration, poke_count))
  File "/home/vanaprastha/anaconda3/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3095, in signal_handler
    raise AirflowTaskTerminated("Task received SIGTERM signal")
airflow.exceptions.AirflowTaskTerminated: Task received SIGTERM signal
[2024-11-27T12:29:00.038-0500] {logging_mixin.py:190} INFO - Task instance in failure state
[2024-11-27T12:29:00.038-0500] {logging_mixin.py:190} INFO - Task start:2024-11-27 17:28:28.328284+00:00 end:2024-11-27 17:29:00.038439+00:00 duration:31.710155
[2024-11-27T12:29:00.039-0500] {logging_mixin.py:190} INFO - Task:<Task(ExternalTaskSensor): wait_current_dag> dag:<DAG: sensor_dag> dagrun:<DagRun sensor_dag @ 2024-11-27 17:25:00+00:00: scheduled__2024-11-27T17:25:00+00:00, state:running, queued_at: 2024-11-27 17:28:11.810627+00:00. externally triggered: False>
[2024-11-27T12:29:00.039-0500] {logging_mixin.py:190} INFO - Failure caused by Task received SIGTERM signal
[2024-11-27T12:29:00.039-0500] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=sensor_dag, task_id=wait_current_dag, run_id=scheduled__2024-11-27T17:25:00+00:00, execution_date=20241127T172500, start_date=20241127T172828, end_date=20241127T172900
[2024-11-27T12:29:00.059-0500] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-11-27T12:29:00.086-0500] {process_utils.py:80} INFO - Process psutil.Process(pid=33725, status='terminated', exitcode=2, started='12:28:27') (33725) terminated with exit code 2
