[2024-11-27T12:33:49.605-0500] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-11-27T12:33:49.618-0500] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sensor_dag.wait_current_dag manual__2024-11-27T17:21:53.619296+00:00 [queued]>
[2024-11-27T12:33:49.627-0500] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sensor_dag.wait_current_dag manual__2024-11-27T17:21:53.619296+00:00 [queued]>
[2024-11-27T12:33:49.627-0500] {taskinstance.py:2866} INFO - Starting attempt 2 of 1
[2024-11-27T12:33:49.647-0500] {taskinstance.py:2889} INFO - Executing <Task(ExternalTaskSensor): wait_current_dag> on 2024-11-27 17:21:53.619296+00:00
[2024-11-27T12:33:49.656-0500] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'sensor_dag', 'wait_current_dag', 'manual__2024-11-27T17:21:53.619296+00:00', '--job-id', '76', '--raw', '--subdir', 'DAGS_FOLDER/PART 3/Sensor/sensor_dag.py', '--cfg-path', '/tmp/tmp6iqm8v__']
[2024-11-27T12:33:49.657-0500] {standard_task_runner.py:105} INFO - Job 76: Subtask wait_current_dag
[2024-11-27T12:33:49.656-0500] {logging_mixin.py:190} WARNING - /home/vanaprastha/anaconda3/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=34010) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-11-27T12:33:49.657-0500] {standard_task_runner.py:72} INFO - Started process 34018 to run task
[2024-11-27T12:33:49.691-0500] {task_command.py:467} INFO - Running <TaskInstance: sensor_dag.wait_current_dag manual__2024-11-27T17:21:53.619296+00:00 [running]> on host VanaPrastha
[2024-11-27T12:33:49.757-0500] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='sensor_dag' AIRFLOW_CTX_TASK_ID='wait_current_dag' AIRFLOW_CTX_EXECUTION_DATE='2024-11-27T17:21:53.619296+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-27T17:21:53.619296+00:00'
[2024-11-27T12:33:49.758-0500] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-11-27T12:33:49.758-0500] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-11-27T12:33:49.758-0500] {logging_mixin.py:190} INFO - Current task name:wait_current_dag state:running start_date:2024-11-27 17:33:49.618577+00:00
[2024-11-27T12:33:49.759-0500] {logging_mixin.py:190} INFO - Dag name:sensor_dag and current dag run status:running
[2024-11-27T12:33:49.759-0500] {taskinstance.py:731} INFO - ::endgroup::
[2024-11-27T12:33:49.759-0500] {baseoperator.py:416} WARNING - ExternalTaskSensor.execute cannot be called outside TaskInstance!
[2024-11-27T12:33:49.759-0500] {external_task.py:258} INFO - Poking for tasks ['end_task'] in dag sensor_sleep on 2024-11-27T17:21:00+00:00 ... 
[2024-11-27T12:33:49.760-0500] {logging_mixin.py:190} WARNING - /home/vanaprastha/anaconda3/lib/python3.12/site-packages/airflow/utils/session.py:97 DeprecationWarning: This method is deprecated and will be removed in future.
[2024-11-27T12:33:50.832-0500] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-11-27T12:33:50.836-0500] {taskinstance.py:2603} INFO - Dependencies not met for <TaskInstance: sensor_dag.wait_current_dag manual__2024-11-27T17:21:53.619296+00:00 [running]>, dependency 'Task Instance State' FAILED: Task is in the 'running' state.
[2024-11-27T12:33:50.838-0500] {taskinstance.py:2603} INFO - Dependencies not met for <TaskInstance: sensor_dag.wait_current_dag manual__2024-11-27T17:21:53.619296+00:00 [running]>, dependency 'Task Instance Not Running' FAILED: Task is in the running state
[2024-11-27T12:33:50.838-0500] {local_task_job_runner.py:166} INFO - Task is not able to be run
[2024-11-27T12:33:52.161-0500] {local_task_job_runner.py:245} INFO - ::endgroup::
[2024-11-27T12:33:52.167-0500] {process_utils.py:132} INFO - Sending 15 to group 34018. PIDs of all processes in the group: [34018]
[2024-11-27T12:33:52.168-0500] {process_utils.py:87} INFO - Sending the signal 15 to group 34018
[2024-11-27T12:33:52.169-0500] {taskinstance.py:3093} ERROR - Received SIGTERM. Terminating subprocesses.
[2024-11-27T12:33:52.173-0500] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/vanaprastha/anaconda3/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vanaprastha/anaconda3/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vanaprastha/anaconda3/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vanaprastha/anaconda3/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vanaprastha/anaconda3/lib/python3.12/site-packages/airflow/sensors/external_task.py", line 348, in execute
    super().execute(context)
  File "/home/vanaprastha/anaconda3/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vanaprastha/anaconda3/lib/python3.12/site-packages/airflow/sensors/base.py", line 334, in execute
    time.sleep(self._get_next_poke_interval(started_at, run_duration, poke_count))
  File "/home/vanaprastha/anaconda3/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3095, in signal_handler
    raise AirflowTaskTerminated("Task received SIGTERM signal")
airflow.exceptions.AirflowTaskTerminated: Task received SIGTERM signal
[2024-11-27T12:33:52.176-0500] {logging_mixin.py:190} INFO - Task instance in failure state
[2024-11-27T12:33:52.177-0500] {logging_mixin.py:190} INFO - Task start:2024-11-27 17:33:49.618577+00:00 end:2024-11-27 17:33:52.176425+00:00 duration:2.557848
[2024-11-27T12:33:52.177-0500] {logging_mixin.py:190} INFO - Task:<Task(ExternalTaskSensor): wait_current_dag> dag:<DAG: sensor_dag> dagrun:<DagRun sensor_dag @ 2024-11-27 17:21:53.619296+00:00: manual__2024-11-27T17:21:53.619296+00:00, state:running, queued_at: 2024-11-27 17:21:53.628656+00:00. externally triggered: True>
[2024-11-27T12:33:52.177-0500] {logging_mixin.py:190} INFO - Failure caused by Task received SIGTERM signal
[2024-11-27T12:33:52.178-0500] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=sensor_dag, task_id=wait_current_dag, run_id=manual__2024-11-27T17:21:53.619296+00:00, execution_date=20241127T172153, start_date=20241127T173349, end_date=20241127T173352
[2024-11-27T12:33:52.212-0500] {taskinstance.py:340} INFO - ::group::Post task execution logs
